# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 228e02468cbf5ebf248824de19184ede1a5f42cdefe9e2e80c29091306c29ec77bf6bb620da864ff5e743321b0d97d27b6abbe8d1a9cc4c9cf1a611c1ae7576c

test:
  secret_key_base: b009243c6ba020a092deacef82a94044e179251c088c36108998589d299168bb5d312481df9a8c63e30837ccfc2d79b7ad837ed0d7ab1a84ab896a2ee7ea316c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
